// Auto-generated file. Do not edit manually.

#include "libft/std.h"

const_string clfw_cl_h_source =
	"/* ************************************************************************** */\n"
	"/*                                                                            */\n"
	"/*                                                        :::      ::::::::   */\n"
	"/*   clfw.cl.h                                          :+:      :+:    :+:   */\n"
	"/*                                                    +:+ +:+         +:+     */\n"
	"/*   By: reclaire <reclaire@student.42mulhouse.f    +#+  +:+       +#+        */\n"
	"/*                                                +#+#+#+#+#+   +#+           */\n"
	"/*   Created: 2024/10/03 10:52:53 by reclaire          #+#    #+#             */\n"
	"/*   Updated: 2024/10/08 04:07:27 by reclaire         ###   ########.fr       */\n"
	"/*                                                                            */\n"
	"/* ************************************************************************** */\n"
	"\n"
	"#ifndef CLFW_CL_H\n"
	"#define CLFW_CL_H\n"
	"\n"
	"#ifndef __OPENCL_VERSION__\n"
	"#define global\n"
	"#define local\n"
	"#define private\n"
	"#define constant\n"
	"#endif\n"
	"\n"
	"#ifndef NULL\n"
	"#define NULL ((void *)0)\n"
	"#endif\n"
	"\n"
	"#define unroll __attribute__((opencl_unroll_hint))\n"
	"\n"
	"typedef unsigned char U8;\n"
	"typedef unsigned short U16;\n"
	"typedef unsigned int U32;\n"
	"#ifdef FT_OS_WIN\n"
	"typedef unsigned long long U64;\n"
	"typedef unsigned long long LU64;\n"
	"#else\n"
	"typedef unsigned long U64;\n"
	"typedef unsigned long long LU64;\n"
	"#endif\n"
	"typedef signed char S8;\n"
	"typedef signed short S16;\n"
	"typedef signed int S32;\n"
	"#ifdef FT_OS_WIN\n"
	"typedef signed long long S64;\n"
	"typedef signed long long LS64;\n"
	"#else\n"
	"typedef signed long S64;\n"
	"typedef signed long long LS64;\n"
	"#endif\n"
	"typedef float F32;\n"
	"typedef double F64;\n"
	"typedef long double LF64;\n"
	"\n"
	"typedef char *string;\n"
	"typedef char const *const_string;\n"
	"typedef int *wstring;\n"
	"typedef int const *const_wstring;\n"
	"typedef int wchar;\n"
	"\n"
	"#ifndef __OPENCL_VERSION__\n"
	"typedef F32 float4 __attribute__((vector_size(sizeof(F32) * 4)));\n"
	"typedef F32 float3 __attribute__((vector_size(sizeof(F32) * 4)));\n"
	"typedef F32 float2 __attribute__((vector_size(sizeof(F32) * 2)));\n"
	"typedef S32 int4 __attribute__((vector_size(sizeof(S32) * 4)));\n"
	"typedef S32 int3 __attribute__((vector_size(sizeof(S32) * 4)));\n"
	"typedef S32 int2 __attribute__((vector_size(sizeof(S32) * 2)));\n"
	"\n"
	"#define vec2(x, y) (t_v2){x, y}\n"
	"#define vec3(x, y, z) (t_v3){x, y, z}\n"
	"#define vec4(x, y, z, w) (t_v4){x, y, z, w}\n"
	"#define ivec2(x, y) (t_iv2){x, y}\n"
	"#define ivec3(x, y, z) (t_iv3){x, y, z}\n"
	"#define ivec4(x, y, z, w) (t_iv4){x, y, z, w}\n"
	"\n"
	"#else\n"
	"#define vec2(x, y) (t_v2)(x, y)\n"
	"#define vec3(x, y, z) (t_v3)(x, y, z)\n"
	"#define vec4(x, y, z, w) (t_v4)(x, y, z, w)\n"
	"#define ivec2(x, y) (t_iv2)(x, y)\n"
	"#define ivec3(x, y, z) (t_iv3)(x, y, z)\n"
	"#define ivec4(x, y, z, w) (t_iv4)(x, y, z, w)\n"
	"#endif\n"
	"\n"
	"typedef float4 t_v4;\n"
	"typedef float3 t_v3;\n"
	"typedef float2 t_v2;\n"
	"typedef int4 t_iv4;\n"
	"typedef int3 t_iv3;\n"
	"typedef int2 t_iv2;\n"
	"\n"
	"\n"
	"typedef struct s_mat4x4\n"
	"{\n"
	"	F32 m00, m10, m20, m30;\n"
	"	F32 m01, m11, m21, m31;\n"
	"	F32 m02, m12, m22, m32;\n"
	"	F32 m03, m13, m23, m33;\n"
	"} t_mat4x4;\n"
	"\n"
	"U64 clfw_get_clock();\n"
	"\n"
	"#endif\n";
